version: '3.4'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - budget-api-network
  gin-budget:
    image: gin-budget-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SRV_PORT=5000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - DB_SSLMODE=disable
      - JWT_SECRET=TJLQMsmsWDAzLGu4UU6BD5XjvB6SRrWK
      - M_PATH=file:/go/src/_migrations
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - budget-api-network
networks:
  budget-api-network:
    driver: bridge 